name: pygeo
channels:
  - conda-forge
  - esri
dependencies:
  - python=3.6
  - gdal
  - h5py
  - netCDF4
  - astropy
  - numpy
  - matplotlib
  - versioned-hdf5
  - opencv
  - wget
  - pandas
  - pytables

